library("ggplot2")
args = commandArgs(trailingOnly = TRUE)
table = read.table("coverage_and_cumulative_kmer_difference")
#Plot 1
xlab_1 = paste(c("log10", args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_1 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_1 = paste(c("Overview of kmer coverage differences between", args[1], "and", args[2], "(log10 scale)"), sep=" ", collapse= " ")
plot1 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+scale_x_log10()+xlab(xlab_1) + ylab(ylab_1) + ggtitle(title_1)
ggsave("x_log_scale_coverage_difference_scatter_plot.png")
#Plot 2
ylab_2 = paste(c("Cumulative kmer coverage difference between", args[1], "and", args[2]), sep=" ", collapse = " ")
title_2 = paste(c("Cumulative sum of kmer coverage differences between", args[1], "and", args[2], "(log10 scale)"), sep=" ", collapse=" ")
plot2 = ggplot(data = table, aes(x=V1,y=V3))+geom_line()+scale_x_log10()+xlab(xlab_1) + ylab(ylab_2) + ggtitle(title_2)
ggsave("x_log_scale_cumulative_sum_kmer_cov_differnces.png")
#Plot 3
xlab_3 = paste(c(args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_3 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_3 = paste(c("Zoomed in view of kmer coverage differences between", args[1], "and", args[2]), sep=" ", collapse= " ")
plot_3 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+xlim(0,10)+ ylim(-1E05,1E05)+xlab(xlab_3) + ylab(ylab_3) + ggtitle(title_3)
ggsave("1E05_ultra_zoomed_in_coverage_difference_scatter_plot.png")
#Plot 4
xlab_4 = paste(c(args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_4 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_4 = paste(c("Overview of kmer coverage differences between", args[1], "and", args[2]), sep=" ", collapse= " ")
plot_4 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+xlab(xlab_4) + ylab(ylab_4) + ggtitle(title_4)
ggsave("coverage_differnce_scatter_plot.png")
#Plot 5
xlab_5 =  paste(c(args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_5 = paste(c("Cumulative kmer coverage difference between", args[1], "and", args[2]), sep=" ", collapse = " ")
title_5 = paste(c("Cumulative sum of kmer coverage differences between", args[1], "and", args[2]), sep=" ", collapse= " ")
plot_5 = ggplot(data = table, aes(x=V1,y=V3))+geom_line()+xlab(xlab_5) + ylab(ylab_5) + ggtitle(title_5)
ggsave("cumulative_sum_kmer_cov_differnces.png")
#Plot 6
xlab_6 = paste(c("log 10", args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_6 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_6 = paste(c("Zoomed in view of kmer coverage differences between", args[1], "and", args[2], "(log10 scale)"), sep=" ", collapse= " ")
plot_6 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+scale_x_log10()+ ylim(-1E05,1E05)+xlab(xlab_6) + ylab(ylab_6) + ggtitle(title_6)
ggsave("1E05_zoomed_in_x_log_scale_coverage_difference_scatter_plot.png")
#Plot 7
xlab_7 = paste(c(args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_7 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_7 = paste(c("Zoomed in view of kmer coverage differences between", args[1], "and", args[2]), sep=" ", collapse= " ")
plot_7 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+ ylim(-1E05,1E05)+xlab(xlab_7) + ylab(ylab_7) + ggtitle(title_7)
ggsave("1E05_zoomed_in_coverage_difference_scatter_plot.png")
#Plot 8
xlab_8 = paste(c(args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_8 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_8 = paste(c("Zoomed in view of kmer coverage differences between", args[1], "and", args[2]), sep=" ", collapse= " ")
plot_8 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+xlim(0,10)+ ylim(-2E05,2E05)+xlab(xlab_8) + ylab(ylab_8) + ggtitle(title_8)
ggsave("2E05_ultra_zoomed_in_coverage_difference_scatter_plot.png")
#Plot 9
xlab_9 = paste(c("log 10", args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_9 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_9 = paste(c("Zoomed in view of kmer coverage differences between", args[1], "and", args[2], "(log10 scale)"), sep=" ", collapse= " ")
plot_9 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+scale_x_log10()+ ylim(-2E05,2E05)+xlab(xlab_9) + ylab(ylab_9) + ggtitle(title_9)
ggsave("2E05_zoomed_in_x_log_scale_coverage_difference_scatter_plot.png")
#Plot 7
xlab_10 = paste(c(args[1], "normalised coverage"), sep=" ", collapse = " ")
ylab_10 = paste(c("(", args[1], "coverage -", args[2], "coverage) * frequency"), sep=" ", collapse = " ")
title_10 = paste(c("Zoomed in view of kmer coverage differences between", args[1], "and", args[2]), sep=" ", collapse= " ")
plot_10 = ggplot(data = table, aes(x=V1,y=V2))+geom_point(alpha=0.6)+ ylim(-2E05,2E05)+xlab(xlab_10) + ylab(ylab_10) + ggtitle(title_10)
ggsave("2E05_zoomed_in_coverage_difference_scatter_plot.png")
